apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: stats-collector
spec:
  selector:
    matchLabels:
      app: stats-collector
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: stats-collector
    spec:
      restartPolicy: Always
      containers:
      - name: stats-container
        imagePullPolicy: Always
        command: [/opt/jumpscale7/bin/influxdumper]
        args: ['--influx-host',  influxdb, '--scan-cidr', agentcontroller/32]
        image: openvcloud/cb_master
