apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: agentcontroller
spec:
  selector:
    matchLabels:
      app: agentcontroller
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: agentcontroller
    spec:
      hostname: agentcontroller
      restartPolicy: Always
      initContainers:
      - name: system-init
        imagePullPolicy: Always
        command: [jspython]
        args: ['configure-system.py', '--roles', 'master,node', '--machineguid', '000000000002', '--controller-addr', '127.0.0.1']
        image: openvcloud/cb_master
        workingDir: /var/run/scripts/system
        volumeMounts:
        - name: system-hrd
          mountPath:  /opt/cfg/system/
        - name: apps-hrd
          mountPath:  /opt/cfg/apps/
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
      containers:
      - name: agentcontroller-container
        imagePullPolicy: Always
        command: [jspython]
        args: ['controller.py', '-i', 'main']
        image: openvcloud/cb_master
        workingDir: /opt/jumpscale7/apps/agentcontroller/
        ports:
        - containerPort: 4444
          name: agent-server
        livenessProbe:
          httpGet:
            path: /ping
            port: agent-server
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: system-hrd
          mountPath: /opt/jumpscale7/hrd/system/
        - name:  apps-hrd
          mountPath: /opt/jumpscale7/hrd/apps/
      - name: jsagent-container
        imagePullPolicy: Always
        command: [jspython]
        args: ['jsagent.py', '-i', 'main']
        image: openvcloud/cb_master
        workingDir: /opt/jumpscale7/apps/jsagent/
        ports:
        - containerPort: 4446
          name: jsagent-serv
        livenessProbe:
          httpGet:
            path: /ping
            port: jsagent-serv
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: system-hrd
          mountPath: /opt/jumpscale7/hrd/system/
        - name:  apps-hrd
          mountPath: /opt/jumpscale7/hrd/apps/
        - name: billing
          mountPath: /opt/jumpscale7/var/resourcetracking/
      - name: redis-container
        imagePullPolicy: Always
        command: [redis-server]
        args: ['--port', '9999', '--bind', '0.0.0.0', '--maxmemory', '100mb']
        image: redis:3.2
        ports:
        - containerPort: 9999
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -p 
            - '9999'
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: system-hrd
        emptyDir: {}
      - name: apps-hrd
        emptyDir: {}
      - name: billing
        hostPath:
          path: /var/ovc/billing
          type: Directory
      - name: system-config
        configMap:
          name: system-config



