apiVersion: v1
kind: Service
metadata:
  name: agentcontroller
  labels:
    name: agentcontroller
spec:
  type: NodePort
  ports:
  - name: main-port
    port: 4444
  selector:
    app: agentcontroller
