apiVersion: v1
kind: Service
metadata:
  name: agentcontroller
  labels:
    name: agentcontroller
spec:
  ports:
  - name: main-port
    port: 4444
    targetPort: 4444
  - name: jsagent-port
    port: 4446
    targetPort: 4446
  - name: redis-port
    port: 9999
    targetPort: 9999



  clusterIP: None
  selector:
    role: agentcontroller