apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-persistant
          mountPath: /var/ovc/grafana
      volumes:
      - name:  grafana-persistant
        hostPath:
          path: /var/ovc/grafana
          type: Directory

