apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
      - name: grafana-init
        command: [jspython]
        args: ['configure-grafana.py']
        image: openvcloud/grafana-init
        workingDir: /var/run/scripts/grafana
        volumeMounts:
        - name: grafana-config
          mountPath:  /opt/cfg/nginx/sites-enabled
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
        - name: grafana-config
          mountPath: /etc/grafana/
      containers:
      - name: grafana-container
        image: grafana/grafana
        env:
        - name: GF_PATHS_CONFIG
          value: "/etc/grafana/grafana.ini"
        ports:
        - containerPort: 3000
          name: graf-serv
        livenessProbe:
          httpGet:
            path: /
            port: graf-serv
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana/
        - name: grafana-provisioning-dashboards
          mountPath: /usr/share/grafana/conf/provisioning/dashboards
        - name: grafana-provisioning-datasources
          mountPath: /usr/share/grafana/conf/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-persistant
          mountPath: /var/lib/grafana
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "grafana-cli admin reset-admin-password --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini admin"]
      volumes:
      - name: grafana-config
        emptyDir: {}
      - name: system-config
        configMap:
          name: system-config
      - name: grafana-provisioning-dashboards
        configMap:
          name: grafana-provisioning-dashboards
      - name: grafana-provisioning-datasources
        configMap:
          name: grafana-provisioning-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-persistant
        hostPath:
          path: /var/ovc/grafana
          type: Directory

