links:
  consume:
    - auto: false
      min: 1
      max: 9999
      role: kubernetes_node
      argname: nodes
    - auto: false
      min: 1
      max: 1
      role: kubernetes_node
      argname: nodes      