links:
  consume:
    - auto: false
      min: 0
      max: 1
      role: controller
      argname: controller
    - auto: false
      min: 1
      max: 1
      role: syncthing
      argname: syncthing
    - auto: false
      min: 0
      max: 1
      role: master
      argname: master


