FROM openvcloud/js9
COPY code/github.com/0-complexity/openvcloud_installer/ /opt/code/github/0-complexity/openvcloud_installer/
CMD ["python3", "/opt/code/github/0-complexity/openvcloud_installer/scripts/install/ninstaller"]
