stages:
  - tag
  - build
  - release

.release_template: &release_definition
  only:
    variables:
      - $VERSION != "9.9.9"

.build_template: &build_definition
  stage: build
  image: openvcloud/imagebuilder
  when: manual

build cb_master:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/cb_master"
build js7:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/js7"
build management:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/management"
build ninstaller:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/ninstaller"
build grafana-init:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/grafana-init"
build nginx:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/nginx"
build nginx-init:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/nginx-init"
build pxeboot:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/pxeboot"
build pxeboot-httpd:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/pxeboot-httpd"
build pxeboot-init:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/pxeboot-init"
build qa:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/qa"
build slightcar:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/slightcar"
build syncthing_sidecar:
  <<: *build_definition
  script: "python3 scripts/buildlib/builder.py scripts/dockers/syncthing_sidecar"
auto build:
  stage: build
  image: openvcloud/imagebuilder
  script: "python3 scripts/buildlib/builder.py --all ."
  only:
    variables:
    - $autobuild

make release tags:
  <<: *release_definition
  image: openvcloud/imagebuilder
  script: "python3 scripts/buildlib/builder.py scripts/dockers/releaser --no-publish"
  stage: tag

make release images:
  <<: *release_definition
  stage: build
  image: openvcloud/imagebuilder
  script: "python3 scripts/buildlib/builder.py --all ."

make release logs:
  <<: *release_definition
  stage: release
