apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: nginx-init
        command: [jspython]
        args: ['configure-nginx.py']
        image: openvcloud/nginx-init
        workingDir: /var/run/scripts/nginx
        volumeMounts:
        - name: nginx-config
          mountPath:  /opt/cfg/nginx/sites-enabled
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
        - name:  ovc-installer-volume
          mountPath: /opt/code/github/openvcloud_installer
          subPath: openvcloud_installer
        - name:  upgrade-config
          mountPath: /opt/cfg/upgrade
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: certs
          mountPath: /opt/cfg/nginx/ssl/
          readOnly: true
        - name:  upgrade-config
          mountPath: /opt/cfg/upgrade
        - name: g8vdc-volume
          mountPath: /opt/code/github/g8vdc
          subPath: g8vdc
        - name: jslib-volume
          mountPath: /opt/code/github/web_python
          subPath: web_python
        - name:  ovc-installer-volume
          mountPath: /opt/code/github/openvcloud_installer
          subPath: openvcloud_installer
        - name: update-log
          mountPath: /opt/logs
      volumes:
        - name: nginx-config
          emptyDir: {}
        - name: upgrade-config
          emptyDir: {}
        - name: update-log
          hostPath:
            path: /var/ovc/updatelogs
            type: Directory
        - name: system-config
          configMap:
            name: system-config
        - name: certs
          hostPath:
            path: /var/ovc/ssl/
            type: Directory
        - name: g8vdc-volume
          gitRepo:
            repository: "https://github.com/0-complexity/g8vdc.git"
        - name: jslib-volume
          gitRepo:
            repository: "https://docs.greenitglobe.com/binary/web_python.git"
        - name: ovc-installer-volume
          gitRepo:
            repository: "https://github.com/0-complexity/openvcloud_installer"



