apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: StatefulSet
metadata:
  name: portal
  namespace: default
spec:
  serviceName: "portal"
  selector:
    matchLabels:
      app: portal
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: portal
    spec:
      initContainers:
      - name: portal-init
        imagePullPolicy: Always
        command: [/opt/jumpscale7/bin/jspython]
        args: ['/opt/cfg/portal/configs.py']
        image: abduman/portal7
        workingDir: /opt/cfg/portal
        volumeMounts:
          - name:  portal-config-vol
            mountPath:  /opt/cfg/portal/portal-config-map.yaml
            subPath: portal-config-map.yaml
          - name:  portal-persistent-storage
            mountPath:  /opt/cfg/portal/hrd
      containers:
      - name: portal-container
        imagePullPolicy: Always
        command: [/bin/bash]
        args: ['-c', '/opt/jumpscale7/bin/jspython /opt/cfg/portal/configs.py && /opt/jumpscale7/bin/jspython portal_start.py main']
        image: abduman/cb_master
        workingDir: /opt/jumpscale7/apps/portals/main
        volumeMounts:
          - name:  portal-config-vol
            mountPath:  /opt/cfg/portal/portal-config-map.yaml
            subPath: portal-config-map.yaml
        ports:
        - containerPort: 82
      - name: redis-container
        imagePullPolicy: Always
        command: [redis-server]
        args: ['--port', '9999', '--bind', '0.0.0.0']
        image: redis:3.2
        ports:
        - containerPort: 9999
      volumes:
      - name: portal-config-vol
        projected:
          sources:
          - secret:
              name: portal-config
      - name:  portal-persistent-storage
        hostPath:
            path: /var/ovc/portal
            type: DirectoryOrCreate



