apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: portal
  namespace: default
spec:
  selector:
    matchLabels:
      app: portal
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: portal
    spec:
      hostname: portal
      initContainers:
      - name: system-init
        imagePullPolicy: Always
        command: [/bin/bash]
        args: ['-c', 'jspython /var/run/scripts/system/configure-system.py --machineguid 000000000003 && jspython /var/run/scripts/portal/configure-portal.py']
        image: openvcloud/cb_master
        workingDir: /var/run/scripts/system
        volumeMounts:
        - name: system-hrd
          mountPath:  /opt/cfg/system/
        - name: versions-manifest
          mountPath:  /opt/cfg/version/versions-manifest.yaml
          subPath: versions-manifest.yaml
        - name: apps-hrd
          mountPath:  /opt/cfg/apps/
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
        - name: ovscred
          mountPath: "/etc/ovscred"
          readOnly: true
      containers:
      - name: portal-container
        imagePullPolicy: Always
        command: [jspython]
        args: [portal_start.py,  main]
        image: openvcloud/cb_master
        workingDir: /opt/jumpscale7/apps/portals/main
        volumeMounts:
        - name:  system-hrd
          mountPath: /opt/jumpscale7/hrd/system/
        - name:  apps-hrd
          mountPath: /opt/jumpscale7/hrd/apps/
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
        - name:  billing
          mountPath: /opt/jumpscale7/var/resourcetracking
        
        ports:
        - containerPort: 82
          name: portal-serv
        livenessProbe:
          httpGet:
            path: /ping
            port: portal-serv
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      - name: jsagent-container
        imagePullPolicy: Always
        command: [/opt/jumpscale7/bin/jspython]
        args: ['jsagent.py', '-i', 'main']
        image: openvcloud/cb_master
        workingDir: /opt/jumpscale7/apps/jsagent/
        volumeMounts:
        - name:  system-hrd
          mountPath: /opt/jumpscale7/hrd/system/
        - name:  apps-hrd
          mountPath: /opt/jumpscale7/hrd/apps/
        ports:
        - containerPort: 4446
          name: jsagent-serv
        livenessProbe:
          httpGet:
            path: /ping
            port: jsagent-serv
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      - name: redis-container
        imagePullPolicy: Always
        command: [redis-server]
        args: ['--port', '9999', '--bind', '0.0.0.0', '--maxmemory', '100mb']
        image: redis
        ports:
        - containerPort: 9999
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -p 
            - '9999'
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: system-hrd
        emptyDir: {}
      - name: apps-hrd
        emptyDir: {}
      - name: billing
        hostPath:
          path: /var/ovc/billing
          type: Directory
      - name: versions-manifest
        configMap:
          name: versions-manifest
      - name: system-config
        configMap:
          name: system-config
      - name: ovscred
        secret:
          secretName: ovs-cred


