apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    name: portal
spec:
  type: ClusterIP
  ports:
  - name: portal
    port: 82
  - name: redis
    port: 9999
  selector:
    app: portal