apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    name: portal
spec:
  type: NodePort
  ports:
  - name: portal
    port: 82
    nodePort: 32000
  - name: redis
    port: 9999
    targetPort: 9999
  selector:
    app: portal