links:
  consume:
    - auto: false
      min: 1
      max: 1
      role: osis
      argname: osis
    - auto: false
      min: 1
      max: 1
      role: agent_controller
      argname: agent_controller

