links:
  consume:
    - auto: false
      min: 1
      max: 1
      role: stats_collector
      argname: stats_collector
    - auto: false
      min: 1
      max: 1
      role: influxdb
      argname: influxdb
    - auto: false
      min: 1
      max: 1
      role: jsagent
      argname: jsagent
