apiVersion: batch/v1
kind: Job
metadata:
  name: upgradejob
spec:
  template:
    metadata:
      labels:
        app: upgrader
    spec:
      restartPolicy: Never
      initContainers:
      - name: nginx-init
        command: [jspython]
        args: ['configure-nginx.py', '--upgrade']
        image: openvcloud/nginx-init
        workingDir: /var/run/scripts/nginx
        volumeMounts:
        - name: nginx-config
          mountPath:  /opt/cfg/nginx/sites-enabled
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
        - name: update-files
          mountPath:  /opt/cfg/upgrade
        - name: update-log
          mountPath: /opt/logs
      containers:
      - name: upgrader-container
        image: openvcloud/management
        volumeMounts:
        - name: ssh-dir
          mountPath: /root/.ssh
        - name: update-log
          mountPath: /opt/logs
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
        - name: kube-client
          mountPath: /usr/local/bin/kubectl
          subPath: kubectl
        command: [bash]
        args: [update_env]
        workingDir: /opt/code/github/0-complexity/openvcloud_installer/scripts/install/
      - name: server-container
        image: openvcloud/nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: update-files
          mountPath: /opt/cfg/upgrade
        - name: update-log
          mountPath: /opt/logs
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: certs
          mountPath: /opt/cfg/nginx/ssl/
          readOnly: true
      volumes:
      - name: ssh-dir
        hostPath:
          path: /var/ovc/.ssh
          type: Directory
      - name: update-log
        hostPath:
          path: /var/ovc/updatelogs
          type: Directory
      - name: update-files
        emptyDir: {}
      - name: system-config
        configMap:
          name: system-config
      - name: nginx-config
        emptyDir: {}
      - name: certs
        hostPath:
          path: /var/ovc/ssl/
          type: Directory
      - name: kube-client
        hostPath:
          path: /usr/local/bin
          type: Directory
