apiVersion: v1
kind: Service
metadata:
  name: zero-access
  labels:
    name: zero-access
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 7022
    targetPort: 22
    protocol: TCP
  - name: http
    port: 5000
    protocol: TCP
  selector:
    app: zero-access