apiVersion: v1
kind: Service
metadata:
  name: zero-access-ssh
  labels:
    name: zero-access-ssh
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    NodePort: 7022
    protocol: TCP
  selector:
    app: zero-access
