apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: osis
spec:
  selector:
    matchLabels:
      app: osis
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: osis
    spec:
      restartPolicy: Always
      initContainers:
      - name: system-init
        imagePullPolicy: Always
        command: [jspython]
        args: ['configure-system.py']
        image: openvcloud/cb_master
        workingDir: /var/run/scripts/system
        volumeMounts:
        - name: cfg-dir
          mountPath: /opt/cfgdir/
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
      containers:
      - name: osis-container
        imagePullPolicy: Always
        command: [/opt/jumpscale7/bin/jspython]
        args: [osisServerStart.py, main]
        image: openvcloud/cb_master
        workingDir: /opt/jumpscale7/apps/osis
        resources:
          limits:
            memory: "2Gi"
        volumeMounts:
          - name:  cfg-dir
            mountPath: /opt/jumpscale7/cfg/
        ports:
        - containerPort: 5544
          name: osis-server
        livenessProbe:
          httpGet:
            path: /ping
            port: osis-server
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: cfg-dir
        emptyDir: {}
      - name: system-config
        configMap:
          name: system-config


