apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: performance
spec:
  selector:
    matchLabels:
      app: performance
  replicas: 1
  template:
    metadata:
      labels:
        app: performance
    spec:
      restartPolicy: Always
      containers:
      - name: js9-container
        imagePullPolicy: Always
        image: openvcloud/js9:9.3.0
        command: ['/bin/bash']
        args: ['-c', '/sbin/init']
        workingDir: /opt/code/github/0-complexity/G8_testing/performance_testing/scripts
