FROM nginx

ADD code/github.com/0-complexity/g8vdc/ /opt/code/github/g8vdc/
ADD code/github.com/0-complexity/openvcloud_installer/ /opt/code/github/openvcloud_installer/
ADD code/docs.greenitglobe.com/binary/web_python/ /opt/code/github/web_python/
