#!/bin/bash

# find phys functions
cfgd=()
pfs=()

function listmlnx(){
	local mlnx
	local i
	local driver
	mlnx=()
	for i in $(readlink /sys/class/net/* | grep pci) ; do
		driver=$(readlink -f /sys/class/net/${i}/device/driver)
		if [ "$( basename $driver )" = "mlx5_core" ] ; then
			mlnx+=( $(basename $i) )
		fi
	done
	echo ${mlnx[@]}
}

function findnew(){
	new=()
	lst=($(listmlnx))
	for i in ${lst[@]} ; do
		skip=
		for j in ${cfgd[@]} ; do
			[ "$i" = "$j" ] && { skip=1 ;break; }
		done
		[[ -n $skip ]] || new+=($i)
	done
	echo ${new[@]}
}

mlnx=( $(listmlnx) )
[ ${#mlnx[@]} -ne 2 ] && exit 1
# save PF
for i in ${mlnx[@]} ; do pfs+=($i) ; done

mlnx=( $(listmlnx) )
for j in ${mlnx[@]} ; do cfgd+=($j) ; done
echo 1 > /sys/class/net/${mlnx[0]}/device/mlx5_num_vfs
vf=$(findnew)
ip link set $vf name storage
# from pfs, get mac addr, set vf's mac
mac=$(cat /sys/class/net/${mlnx[0]}/address)
start=51
vfmac=00:${start}${mac:5}
ip link set storage mtu 9000

ip link set ${mlnx[0]} vf 0 mac ${vfmac}
ip link set storage address ${vfmac}

