apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: qa
spec:
  selector:
    matchLabels:
      app: qa
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: qa
    spec:
      restartPolicy: Always
      containers:
      - name: qa-container
        imagePullPolicy: Always
        image: openvcloud/qa
        command: ['/bin/bash']
        args: ['-c', 'jspython /var/run/scripts/system/configure-system.py && /sbin/my_init']
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/code/github/0-complexity/openvcloud_installer/scripts/install/:/opt/code/github/0-complexity/openvcloud_installer/scripts/install/
        volumeMounts:
          - name:  system-config
            mountPath: /opt/cfg/system
          - name: authorized-keys
            mountPath: /root/.ssh/authorized_keys
            subPath: authorized_keys
          - name: tun-device
            mountPath: /dev/net/tun
            subPath: tun
        ports:
        - containerPort: 2205
      volumes:
      - name: system-config
        configMap:
          name: system-config
      - name: authorized-keys
        secret:
          secretName: tester-keys
          defaultMode: 0600
      - name: tun-device
        hostPath:
          path: /dev/net/
          type: Directory



