apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: qa
spec:
  selector:
    matchLabels:
      app: qa
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: qa
    spec:
      restartPolicy: Always
      containers:
      - name: qa-container
        imagePullPolicy: Always
        image: openvcloud/cb_master
        workingDir: /var/run/scripts/system
        command: ['/bin/bash']
        args: ['-c', 'jspython configure-system.py && /sbin/my_init']
        env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/code/github/0-complexity/openvcloud_installer/scripts/install/:/opt/code/github/0-complexity/openvcloud_installer/scripts/install/
        volumeMounts:
          - name:  system-config
            mountPath: /opt/cfg/system
          - name: installer-volume
            mountPath: /opt/code/github/0-complexity/openvcloud_installer
            subPath: openvcloud_installer
          - name: authorized-keys
            mountPath: /root/.ssh/authorized_keys
            subPath: authorized_keys
          - name: tun-device
            mountPath: /dev/net/
            subPath: tun
        ports:
        - containerPort: 2205
      volumes:
      - name: system-config
        configMap:
          name: system-config
      - name: authorized-keys
        secret:
          secretName: tester-keys
          defaultMode: 0600
      - name: tun-device
        hostPath:
          path: /dev/net/
          type: Directory
      - name: installer-volume
        gitRepo:
          repository: "https://github.com/0-complexity/openvcloud_installer.git"



