apiVersion: v1
kind: Service
metadata:
  name: qa
  labels:
    name: qa
spec:
  type: NodePort
  externalIPs:
  - 10.101.109.1 
  - 10.101.109.2 
  - 10.101.109.3
  ports:
  - name: ssh
    targetPort: 22
    port: 22
    nodePort: 32222
  selector:
    app: qa
