apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: management
spec:
  selector:
    matchLabels:
      app: management
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: management
    spec:
      restartPolicy: Always
      containers:
      - name: teleport-container
        imagePullPolicy: Always
        image: openvcloud/teleport
        command: ['/usr/bin/python3']
        args: ['/var/run/scripts/teleport/start-teleport.py']
        workingDir: /var/run/scripts/teleport/
        ports:
          - containerPort: 3080
          - containerPort: 3022
        volumeMounts:
          - name:  system-config
            mountPath: /opt/cfg/system
          - name: ssh-dir
            mountPath: /root/.ssh
          - name: teleport-config
            mountPath: /var/lib/teleport/
          - name: root-certs
            mountPath: /opt/cfg/ssl/
            readOnly: true
      - name: management-container
        imagePullPolicy: Always
        image: openvcloud/management
        command: ['/bin/bash']
        args: ['-c', 'python3 /var/run/init-ssh.py --teleport && /sbin/my_init']
        env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/code/github/0-complexity/openvcloud_installer/scripts/install/
        - name: ENV_CONFIG
          value: /opt/cfg/system/system-config.yaml
        volumeMounts:
          - name:  system-config
            mountPath: /opt/cfg/system
          - name: teleport-config
            mountPath: /var/lib/teleport/
          - name: installer-volume
            mountPath: /opt/code/github/0-complexity/openvcloud_installer
            subPath: openvcloud_installer
          - name: ssh-dir
            mountPath: /root/.ssh
        ports:
        - containerPort: 2205
      volumes:
      - name: system-config
        configMap:
          name: system-config
      - name: teleport-config
        emptyDir: {}
      - name: ssh-dir
        hostPath:
          path: /var/ovc/.ssh
          type: Directory
      - name: root-certs
        secret:
          secretName: root-certs
      - name: installer-volume
        gitRepo:
          repository: "https://github.com/0-complexity/openvcloud_installer.git"



