apiVersion: v1
kind: Service
metadata:
  name: management
  labels:
    name: management
spec:
  type: NodePort
  ports:
  - name: ssh
    targetPort: 2205
    port: 7023
  selector:
    app: management
