apiVersion: v1
kind: Service
metadata:
  name: management
  labels:
    name: management
spec:
  type: NodePort
  ports:
  - name: ui
    port: 3080
  - name: management-ssh
    port: 2205
  - name: teleport-ssh
    port: 3022
  externalIPs:
  - 10.101.109.1
  - 10.101.109.2
  - 10.101.109.3
  selector:
    app: management
