apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: management
spec:
  selector:
    matchLabels:
      app: management
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: management
    spec:
      hostNetwork: true
      restartPolicy: Always
      containers:
      - name: management
        imagePullPolicy: Always
        image: openvcloud/management
        command: ['/bin/bash']
        args: ['-c', 'python3 /var/run/init-ssh.py && /sbin/my_init']
        volumeMounts:
          - name:  system-config
            mountPath: /opt/cfg/system
        ports:
        - containerPort: 22
      volumes:
      - name: system-config
        configMap:
          name: system-config



