apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pxeboot
spec:
  selector:
    matchLabels:
      app: pxeboot
  replicas: 1
  template:
    metadata:
      labels:
        app: pxeboot
    spec:
      hostNetwork: true
      containers:
      - name: pxeboot
        image: openvcloud/pxeboot
        volumeMounts:
        - name: pxeboot-root
          mountPath: /pxeboot
      #
      # add here container which do http and images
      #
      initContainers:
      - name: pxeboot-init
        image: openvcloud/pxeboot-init
        command:
        - bash
        - /usr/local/bin/pxeboot-init
        volumeMounts:
        - name: system-config
          mountPath: "/etc/global"
        - name: pxeboot-root
          mountPath: /opt/pxeboot
      volumes:
      - name: system-config
        configMap:
          name: system-config
      - name: pxeboot-root
        hostPath:
          path: /var/ovc/pxeboot
          type: DirectoryOrCreate

