apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana/grafana:master
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-provisioning-dashboards
          mountPath: /usr/share/grafana/conf/provisioning/dashboards
        - name: grafana-provisioning-datasources
          mountPath: /usr/share/grafana/conf/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: grafana-persistant
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-provisioning-dashboards
        configMap:
          name: grafana-provisioning-dashboards
      - name: grafana-provisioning-datasources
        configMap:
          name: grafana-provisioning-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-persistant
        hostPath:
          path: /var/ovc/grafana
          type: Directory

