apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pxeboot
spec:
  selector:
    matchLabels:
      app: pxeboot
  replicas: 1
  template:
    metadata:
      labels:
        app: pxeboot
    spec:
      hostNetwork: true
      containers:
      - name: pxeboot
        image: openvcloud/pxeboot
        volumeMounts:
        - name: pxeboot-root
          mountPath: /pxeboot
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        lifecycle:
          preStop:
            exec:
              command: ["/usr/local/bin/destroy"]
      - name: pxeboot-httpd
        image: openvcloud/pxeboot-httpd
        volumeMounts:
        - name: pxeboot-images
          mountPath: /www
        - name: pxeboot-root
          mountPath: /pxeboot
      initContainers:
      - name: pxeboot-init
        image: openvcloud/pxeboot-init
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        command:
        - bash
        - /usr/local/bin/pxeboot-init
        volumeMounts:
        - name: system-config
          mountPath: "/etc/global"
        - name: pxeboot-root
          mountPath: /opt/pxeboot
      volumes:
      - name: system-config
        configMap:
          name: system-config
      - name: pxeboot-root
        hostPath:
          path: /var/ovc/pxeboot
          type: DirectoryOrCreate
      - name: pxeboot-images
        hostPath:
          path: /var/ovc/pxeboot/images
          type: DirectoryOrCreate

