apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb-container
        imagePullPolicy: Always
        command: [influxd]
        image: influxdb:1.4
        ports:
        - containerPort: 8088
        - containerPort: 8086
        - containerPort: 8082
        - containerPort: 2003
        - containerPort: 25826
        - containerPort: 4242
        - containerPort: 8089
      volumes:
        - name:  influxdb-persistent-storage
          hostPath:
            Path to mount: /var/ovc/influx




