apiVersion: v1
kind: Service
metadata:
  name: syncthing
  labels:
    name: syncthing
spec:
  ports:
  - port: 8384
    targetPort: 8384
    name: webui
#  - port: 22000
#    targetPort: 22000
#    name: sync
  selector:
    role: syncthing
  type: NodePort
