apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: syncthing
spec:
  serviceName: "syncthing"
  replicas: 3
  template:
    metadata:
      labels:
        role: syncthing
    spec:
      affinity: # only one per node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - syncthing
            topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
      - name: syncthing
        image: syncthing/syncthing
        ports:
        - containerPort: 8384
        - containerPort: 22000
        volumeMounts:
        - name: syncthing-persistant
          mountPath: /var/ovc
      - name: syncthing-sidecar
        image: maxux/syncthing_sidecar
        env:
        - name: HOST_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name:  syncthing-persistant
        hostPath:
          path: /var/ovc
          type: Directory

