apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: syncthing
spec:
  serviceName: "syncthing"
  replicas: 3
  template:
    metadata:
      labels:
        role: syncthing
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      affinity: # only one per node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - syncthing
            topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 2
      containers:
      - name: syncthing
        image: syncthing/syncthing
        ports:
        - containerPort: 8384
        - containerPort: 22000
        volumeMounts:
        - name: syncthing-persistant
          mountPath: /var/ovc
        - name: sync-config
          mountPath: /var/syncthing/config
        command: ['/bin/syncthing']
        args: ["-home", "/var/syncthing/config", "-gui-address", "0.0.0.0:8384"]
      - name: syncthing-sidecar
        image: openvcloud/syncthing_sidecar
        env:
        - name: HOST_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name:  system-config
          mountPath:  /opt/cfg/system/system-config.yaml
          subPath: system-config.yaml
        - name: sync-config
          mountPath: /var/syncthing/config
      volumes:
      - name:  syncthing-persistant
        hostPath:
          path: /var/ovc
          type: Directory
      - name: system-config
        configMap:
          name: system-config
      - name: sync-config
        emptyDir: {}

